version: '3.8'
services:
    database:
        image: mysql
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./build:/var/lib/
        ports:
            - '3307:3306'
        networks:
            - backend
        env_file:
            - .env
    php-apache:
        container_name: php-apache
        restart: unless-stopped
        build:
            dockerfile: ./build/apache/Dockerfile
        ports:
            - '8080:80'
        networks:
            - backend
        volumes:
            - ./build/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - database
networks:
        backend:
            driver: bridge
